# -*- coding: utf-8 -*-
"""LGM 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpbFeMi7jEjtcA9opwWyCtrTfTcDqZN5

LetsGrowMore Virtual Internship Program (Dec 2021 - Jan 2022)

Author : Komal Patil

Task 2 : Image to Pencil Sketch with Python

Level : Begineer

In this task we have to connect a given image into its pencil sketch using python. In these we use CV(Computer Vision) library and pillow module for the image Processing.

Importing Libraries
"""

import cv2
import numpy as np
from PIL import Image
from IPython.display import display

"""Loading the Image"""

img = cv2.imread("img.jpg")

img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

display(Image.fromarray(img))

"""Converting Image to Greyscale Image"""

grayImg = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
display(Image.fromarray(grayImg))

"""Inverting the Grayscale Mage"""

inv_grayImg = 255 -grayImg

inv_grayImg

display(Image.fromarray(inv_grayImg))

"""Blur the Image"""

blur_img = cv2.GaussianBlur(inv_grayImg,(35,35),0)

display(Image.fromarray(blur_img))

"""Mixing the grayscale image and inverted blur image"""

inv_bluring = 255 - blur_img

inv_bluring

display(Image.fromarray(inv_bluring))

def mix(grayImg, blur_img):
  return cv2.divide(grayImg, inv_bluring, scale = 210)

pencil_sketch = mix(grayImg, inv_bluring)
display(Image.fromarray(pencil_sketch))